name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 6'
defaults:
  run:
    shell: bash
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Hatch
        run: |
          pip install hatch
      - name: Install dependencies
        run: |
          hatch run style:pip freeze
          hatch run types:pip freeze
      - name: Check style
        if: always()
        run: |
          hatch run style:fix
      - name: Check formatting
        if: always()
        run: |
          git diff --color --exit-code
      - name: Check types
        if: always()
        run: |
          hatch run types:check
